# Generated by Django 4.1.13 on 2024-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member_address_member_avatar_member_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
